AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  PublicSubnet1:
    Type: String
    Default: subnet-01a79e54dd1a0064c
  PublicSubnet2:
    Type: String
    Default: subnet-0927958e96802d4df
  PrivateSubnet1:
    Type: String 
    Default: subnet-0dcbe5dc23cad4fae
  PrivateSubnet2:
    Type: String
    Default: subnet-04dafc6015a245202


Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ECS-ToDoApp-Cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ToDoAPP-log-group
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ToDoApp-Deployment-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ToDoAppSecurityGroup
      GroupDescription: Security group for ToDpApp container
      VpcId: vpc-0c6c0a488ab519e12
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ToDoApp-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: ToDoAPP-container
          Image: 585781887322.dkr.ecr.ap-southeast-2.amazonaws.com/jenkins/todoapp:202111051557
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: ToDoApp-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref PublicSubnet1
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId