#! /bin/bash -e
#
# Publish Docker image

set -eux
cd $(dirname $0)/..

mkdir -p artifacts
TZ=Australia/Melbourne date +'%Y%m%d%H%M' >artifacts/version.txt
VERSION=$(cat artifacts/version.txt)
TAG="585781887322.dkr.ecr.ap-southeast-2.amazonaws.com/jenkins/todoapp:${VERSION}"

docker build -t $TAG .
docker push $TAG
