#! /bin/bash -e
#
# Publish Docker image

cd $(dirname $0)/..

#Log in to ECR
aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 585781887322.dkr.ecr.ap-southeast-2.amazonaws.com

REPOSITORY="585781887322.dkr.ecr.ap-southeast-2.amazonaws.com/todoapp"
VERSION=$(TZ=Australia/Melbourne date +'%Y%m%d%H%M')

docker build -t ${REPOSITORY}:${VERSION} .


# Release to new registry                                                                                                                                                                                                                                                                           

docker tag ${REPOSITORY}:${VERSION} ${REPOSITORY}:latest
docker push ${REPOSITORY}:latest

# Save image reference
mkdir -p artifacts
DIGEST=$(docker pull ${REPOSITORY}:${VERSION} | sed -n 's/^Digest: // p')
IMAGE="${REPOSITORY}:${VERSION}@${DIGEST}"
echo "$IMAGE" > artifacts/docker-image.txt
echo "Released as: $IMAGE"
