#! /bin/bash -e
#
# Publish Docker image

cd $(dirname $0)/..

REPOSITORY="585781887322.dkr.ecr.ap-southeast-2.amazonaws.com/todoapp"
VERSION=$(TZ=Australia/Melbourne date +'%Y%m%d%H%M')

docker build -t ${REPOSITORY}:${VERSION} .

# Release to new registry
docker push ${REPOSITORY}:${VERSION}
docker tag ${REPOSITORY}:${VERSION} ${REPOSITORY}:latest
docker push ${REPOSITORY}:latest

# Save image reference
mkdir -p artifacts
DIGEST=$(docker pull ${REPOSITORY}:${VERSION} | sed -n 's/^Digest: // p')
IMAGE="${REPOSITORY}:${VERSION}@${DIGEST}"
echo "$IMAGE" > artifacts/docker-image.txt
echo "Released as: $IMAGE"
